Repository ntedgi/node-efficientnet, pull requests merged in 2021-03, with the labels that each got.

#24 feature/test-code-climate-integration
  example.ts
  src/EfficientnetModel.ts
Labels: enhancement

#28 feat: add `localModelRootDirectory` options
  README.md
  package.json
  src/EfficientNetCheckPointFactory.ts
  src/EfficientnetModel.ts
  tests/model.test.js
Labels: enhancement, good first issue

#29 Feature/add support to run tensorflow model on gpu #15
  package.json
  src/EfficientNetCheckPointFactory.ts
  src/EfficientnetModel.ts
Labels: enhancement

#33 feature/reduce tests time load from local dir
  example.ts
  playground/server/Dockerfile
  playground/server/index.js
  playground/server/package.json
  tests/model.test.js
Labels: tests 🧪

#32 feature / support `i18n`
  README.md
  misc/labels_map.json
  package.json
  src/EfficientNetResult.ts
  src/EfficientnetModel.ts
  tests/model.test.js
Labels: enhancement
