Repository ntedgi/node-efficientnet, pull requests merged in 2022-10, with the labels that each got.

#74 add CUSTOM_ELEMENTS_SCHEMA to app.module
  playground/ui/src/app/app.module.ts
Labels: hacktoberfest, hacktoberfest-accepted

#76 Updated karma dev dependency
  playground/ui/package.json
Labels: hacktoberfest, hacktoberfest-accepted

#77 chores: playground server codebase & dependencies cleanup
  .eslintrc
  playground/server/__tests__/server.test.js
  playground/server/index.js
  playground/server/package.json
  playground/server/server.js
Labels: first-timers-only, hacktoberfest, hacktoberfest-accepted

#75 Add unit test to complete coverage of server code
  playground/server/__tests__/server.test.js
Labels: hacktoberfest, hacktoberfest-accepted

#89 Fix libs change issue for playground tests
  package.json
Labels: hacktoberfest, hacktoberfest-accepted, dependencies

#72 Feature/language support
  example.ts
  playground/server/__tests__/server.test.js
  playground/server/server.js
  playground/ui/package.json
  playground/ui/src/app/app.module.ts
  playground/ui/src/app/imageuploader/imageuploader.component.html
  playground/ui/src/app/imageuploader/imageuploader.component.scss
  playground/ui/src/app/imageuploader/imageuploader.component.ts
  playground/ui/src/app/languages-api.service.spec.ts
  playground/ui/src/app/languages-api.service.ts
  playground/ui/src/app/primeng-imports.ts
  playground/ui/src/app/uploader/uploader.component.html
  playground/ui/src/app/uploader/uploader.component.ts
  playground/ui/src/proxy.conf.json
  src/EfficientnetModel.ts
Labels: help wanted, playground 🧩, tests 🧪, hacktoberfest

#80 feat: adds russian lang support for the model
  README.md
  src/EfficientNetLanguageProvider.ts
  src/misc/ru.json
  tester/tests/language-provider.test.js
  tests/language-provider.test.js
Labels: documentation 📚, enhancement, first-timers-only, hacktoberfest, hacktoberfest-accepted, dependencies

#104 Update README.md
  README.md
Labels: enhancement, first-timers-only, hacktoberfest, hacktoberfest-accepted

#78 feature: French language support
  README.md
  src/EfficientNetLanguageProvider.ts
  src/misc/fr.json
  tests/language-provider.test.js
Labels: help wanted, tests 🧪, first-timers-only, hacktoberfest, hacktoberfest-accepted

#79 adding Hebrew translation for image net labels
  README.md
  index.ts
  src/EfficientNetCheckPointFactory.ts
  src/EfficientNetLanguageProvider.ts
  src/EfficientnetModel.ts
  src/misc/he.json
  tests/language-provider.test.js
  tests/model.test.js
Labels: enhancement, help wanted, first-timers-only, hacktoberfest, hacktoberfest-accepted

#106 release 2.1.0 , fix unstable specs
  .npmignore
  package.json
  playground/server/__tests__/server.test.js
  playground/server/package-lock.json
  playground/server/package.json
  playground/server/server.js
Labels: documentation 📚, hacktoberfest, hacktoberfest-accepted
